### ISSUE TITLE
Allow customizing base images for hub, proxy and culler pods

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/helm-chart#1]
Some installations (such as Wikimedia's) require that all container images derive from a pre-approved list. We can probably do this pretty easily, and we should!

**Comment by minrk** [comment]
Makes sense. What's the best way to accomplish this? Do you want to allow customizing the FROM lines but still run the builds? Or allow customizing the whole image, since there are assumptions made about the base image in the rest of the Dockerfile (e.g. ubuntu, pip3, etc.).

**Comment by yuvipanda** [comment]
You can do this now - setting a prefix. That's good enough for wikimedia for now :)
