### ISSUE TITLE
Error: failed to download "jupyterhub/jupyterhub"

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/helm-chart#103]
Hi,

I am trying to download/install the jupyterhub helm chart.

`helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/`
"jupyterhub" has been added to your repositories

`helm repo update`
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "jupyterhub" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

`helm upgrade --install jhub jupyterhub/jupyterhub --namespace jhub --version="0.8.2" --values config.yaml
`Error: failed to download "jupyterhub/jupyterhub" (hint: running `helm repo update` may help)

`helm repo list`
NAME      	URL
stable    	https://kubernetes-charts.storage.googleapis.com
local     	http://127.0.0.1:8879/charts
jupyterhub	https://jupyterhub.github.io/helm-chart/

what am i missing? could it be upstream repo server issue?

**Comment by wierzba3** [comment]
Wow. The problem was that I had quotes around the version. it did not accept that. This works:
```
helm upgrade --install jhub jupyterhub/jupyterhub --namespace jhub --version=0.8.2 --values config.yaml 
```

**Comment by adriendelsalle** [comment]
Hi @wierzba3 
Could you please consider closing this issue if it is resolved?
Thanks!

**Comment by consideRatio** [comment]
I realize I wasn't "Watching" this repo on GitHub - thanks for the ping @adriendelsalle
