### ISSUE TITLE
Automate update of information

### ISSUE THREAD

**Issue by adriendelsalle** [jupyterhub/helm-chart#106]
Thank you for this source of information!

I was a bit lost initially using JHub on kube between the Hub version and its helm chart version, see https://github.com/jupyterhub/jupyterhub/issues/3012.

Would it be possible to automate update of the README.md of this repo when tagging/building the helm chart from the Z2JH project?
The 0.9.0 version of helm chart using JHub 1.1.0 is currently missing from this repo.

Thanks!

**Comment by adriendelsalle** [comment]
ping @consideRatio 
Could you please review?
Thanks!

**Comment by consideRatio** [comment]
The issue with automation is that it is one other piece that can break, require maintenance, and documentation so everybody in the open source project can understand it.

I don't find it easy enough to automate this to motivate this automation, but I'll update the version mapping manually now.

**Comment by consideRatio** [comment]
Done!

Thanks for reporting this @adriendelsalle ! :heart:

**Comment by manics** [comment]
The app version should be in the `Chart.yaml`, so it might be possible to automatically read and incorporate it into the page using jekyll. I'll investigate.....

**Comment by manics** [comment]
See for example https://www.manicstreetpreacher.co.uk/kubernetes-omero/
It's ages since I've updated that, so I'll have to see how to port those changes to here

**Comment by manics** [comment]
https://github.com/jupyterhub/helm-chart/pull/107 was merged! You can see the JupyterHub versions on https://jupyterhub.github.io/helm-chart/

**Comment by adriendelsalle** [comment]
Great job! Thanks @manics !
