### ISSUE TITLE
SyncLoadBalancerFailed

### ISSUE THREAD

**Issue by DROMZEE** [jupyterhub/helm-chart#111]
### Bug description

```EXTERNAL-IP``` stay on ```<pending>``` 

With this command

```kubectl --namespace=jupyterhub get svc proxy-public```

#### Expected behaviour

value of ```EXTERNAL-IP```

#### Actual behaviour

> Warning  SyncLoadBalancerFailed  7m3s                 service-controller  Error syncing load balancer: failed to ensure load balancer: error waiting for load balancer to be deployed Get https://loadbalancer.eu.ovhapis.com/1.0/cloud/project/454c02d9087c4e1695f522524a5dda60/loadbalancer: context deadline exceeded

with command 
```kubectl describe service proxy-public --namespace jupyterhub```

### How to reproduce

```helm upgrade --install jhub jupyterhub/jupyterhub --namespace jupyterhub --version=0.9.1 --values config.yaml```

### Your personal set up

 - OS: Windows 10
 - Version: 0.9.1
 - Configuration: helm version 3.2.4

**Comment by erniee** [comment]
@DROMZEE I don't see where you created your namespace.  Which is required for Helm 3.
Its bitten me in the past. 
`helm upgrade --install jhub jupyterhub/jupyterhub --namespace jupyterhub --create-namespace --version=0.9.1 --values config.yaml`
