### ISSUE TITLE
Debug artifact hub config

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/helm-chart#119]
#114, #115, #116, #117 --- It seems like artifact hub doesn't identify the file... I'm clueless why and there doesn't seem to be any logs.

## References
1. Artifact Hub (AH) [docs on Helm chart repos](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#helm-charts-repositories)
2. AH [note about making artifacthub-repo.yml available next to index.yaml](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#verified-publisher)
   > Please note that the artifacthub-repo.yml metadata file must be located at the repository URL's path. In Helm repositories, for example, this means it must be located at the same level of the chart repository index.yaml file, and it must be served from the chart repository HTTP server as well.
3. Proof that we publish at https://jupyterhub.github.io/helm-chart/artifacthub-repo.yml next to https://jupyterhub.github.io/helm-chart/index.yaml

**Comment by manics** [comment]
Have you opened an issue on artifacthub?

**Comment by consideRatio** [comment]
Now I have: https://github.com/artifacthub/hub/issues/1045

**Comment by consideRatio** [comment]
Apparently it only reprocess what to publish etc when index.yaml change in some way, closing as solved!

**Comment by manics** [comment]
Do we need a separate issue to get it labelled as "Official"?

**Comment by consideRatio** [comment]
Yepp, that wouldbe #117 - verified is like prooving control of the Helm chart repo content, while official is manually reviewed as I understand and indicates that the JupyterHub helm chart repo contains is the official place to get JupyterHub stuff.
