### ISSUE TITLE
Error Function "dig" not defined

### ISSUE THREAD

**Issue by Madaditya** [jupyterhub/helm-chart#126]
### Bug description

Unable to install the helm chart using 
`helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/`  
`helm repo update`
`helm install jupyterhub/jupyterhub jhub`

#### Expected behaviour

Chart should install successfully

#### Actual behaviour

`Error: parse error at (jupyterhub/templates/hub/_helpers-passwords.tpl:35): function "dig" not defined`

### Your personal set up

 - Version(s):
Kubernetes version : 1.20
Helm Chart : 1.0.0
Provider : AWS (EKS)

**Comment by consideRatio** [comment]
Hi! See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2234#issuecomment-849591922
