### ISSUE TITLE
ingress: Additional property ingressClassName is not allowed

### ISSUE THREAD

**Issue by rafagsiqueira** [jupyterhub/helm-chart#130]
### Bug description

Can't set the ingressClassName for the ingress on the values.yaml.

#### Expected behaviour

With the deprecation of the ingress class annotation, the helm chart should accept ingressClassName as a parameter for the ingress.

#### Actual behaviour

Error ingress: Additional property ingressClassName is not allowed.

### How to reproduce

Set: 
ingress:
  enabled: true
  ingressClassName: nginx
on values.yaml and try do install the helm release.
### Your personal set up

- Kubernetes: 1.21.2

**Comment by consideRatio** [comment]
The jupyterhub Helm chart is maintained in jupyterhub/zero-to-jupyterhub-k8s. ingressClassName is supported, but a release has not been made to include it.
