### ISSUE TITLE
https://jupyterhub.github.io/helm-chart/index.yaml doesn't available

### ISSUE THREAD

**Issue by roma-glushko** [jupyterhub/helm-chart#131]
### Bug description

Connection to https://jupyterhub.github.io/helm-chart/ gets refused when using Helm:

```
"jupyterhub" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "jupyterhub" chart repository (https://jupyterhub.github.io/helm-chart/):
        Get "https://jupyterhub.github.io/helm-chart/index.yaml": dial tcp 185.199.108.153:443: connect: connection refused
Update Complete. ⎈Happy Helming!⎈
history.go:56: [debug] getting history for release jupyterhub-test
Release "jupyterhub-test" does not exist. Installing it now.
install.go:173: [debug] Original chart version: ""
Error: Get "https://jupyterhub.github.io/helm-chart/jupyterhub-1.2.0.tgz": dial tcp 185.199.108.153:443: connect: connection refused
helm.go:88: [debug] Get "https://jupyterhub.github.io/helm-chart/jupyterhub-1.2.0.tgz": dial tcp 185.199.108.153:443: connect: connection refused
```

or when trying to request the URL via wget or browser:

```
(base) ➜  jupyterhub git:(rhlushko/jupyter-eg-debugging) ✗ wget https://jupyterhub.github.io/helm-chart/index.yaml
--2022-01-16 00:42:32--  https://jupyterhub.github.io/helm-chart/index.yaml
Resolving jupyterhub.github.io (jupyterhub.github.io)... 185.199.108.153, 185.199.111.153, 185.199.110.153, ...
Connecting to jupyterhub.github.io (jupyterhub.github.io)|185.199.108.153|:443... 
```

<img width="1790" alt="Screen Shot 2022-01-16 at 00 49 56" src="https://user-images.githubusercontent.com/9402690/149640087-6bbeed94-ae8a-47ff-9e8d-91848a4bae87.png">

#### Expected behaviour

https://jupyterhub.github.io/helm-chart/  responds quickly to requests and let helm download charts of needed version.

#### Actual behaviour

Connection gets refused when requesting the https://jupyterhub.github.io/helm-chart/ URL.

**Comment by manics** [comment]
The Helm chart is hosted on GitHub pages, so this was most likely a temporary problem with GitHub or your network provider.

**Comment by roma-glushko** [comment]
> your network provider
How would I leave this issue then? The rest of the website are loading well. 

The https://jupyterhub.github.io/helm-chart/ loaded once when I was AFK but now it's still hanging out for a long time :/
