### ISSUE TITLE
'singleuser.image.pullPolicy' of config.yaml is never being used.

### ISSUE THREAD

**Issue by uriart** [jupyterhub/helm-chart#139]
### Bug description

'singleuser.image.pullPolicy' of config.yaml is never being used, however we can find it in the [documentation](https://z2jh.jupyter.org/en/latest/resources/reference.html#singleuser-image-pullpolicy) as if it were confgiurable.

#### Expected behaviour

Change imagePullPolicy value.

#### Actual behaviour

Not changing.

### How to reproduce

1. install Helm Chart in minikube
2. Try using custom-netbook:latest image form local daemon.
3. hook-image-puller, will always try to do the pull from external repol and fail.

### Your personal set up

 - OS:
ubuntu 20.04
 - Version(s):
jupyter helm chart 2.0.0
kubernetes: v1.26.7
Docker 24.0.4

**Comment by consideRatio** [comment]
> #### Expected behaviour
> Change imagePullPolicy value.

It is influencing the imagePullPolicy _of the user servers started by KubeSpawner_. But its not influencing the hook-image-puller and continuous-image-puller pods, which isn't obvious it should or shouldn't. The purpose of those pods is to ensure images are pulled to nodes. Should they or should they not be influenced by the same image pull policy configured for user servers?

Is it your expectation that they should have the same image pull policy as the user servers?

Related template logic:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/6ea5041364647371244224971cb20f195d283251/jupyterhub/templates/image-puller/_helpers-daemonset.tpl#L77-L174

**Comment by uriart** [comment]
Ok I understand. The problem I had is trying to use an image from my local docker daemon tagged '_latest_'. Kubernetes will always default to '_imagePullPolicy: Allways_' if the image is tagged with '_latest_' and I couldn't find a way to change it to '_Never_' in the chart's config.yaml. 
I was able to solve it by tagging the image differently than '_latest_'.
