### ISSUE TITLE
Add support for manually setting up SSL certs

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/helm-chart#14]
Let's encrypt support in the long run would be nice, but until then allow manually specifying SSL for the proxy.

**Comment by minrk** [comment]
I can work on letsencrypt, too. I've automated it enough times with ansible for tmpnb/nbviewer now that doing it here shouldn't be too tough.

**Comment by yuvipanda** [comment]
For let's encrypt, the 'right thing' is to just use https://github.com/jetstack/kube-lego and wait for proxy integration in 0.8. I'd rather not invent something we've to maintain ourselves. manual SSL setup is needed anyway (for places like berkeley) and a stopgap until we get letsencrypt.

**Comment by aliasmrchips** [comment]
👍

**Comment by yuvipanda** [comment]
Note that we do support this now. Just needs documentation.

**Comment by aculich** [comment]
@henchc @jeffbacon at D-Lab have an immediate-need use case for this. If you could paste the minimum info in here we can send a pull request to the full documentation to document it fully. :)

**Comment by aculich** [comment]
https://hackmd.io/CYNgjKDsIEwLQGMCmBWALHNsVwIYlwwGYw0ZRdIAjXADhSA=

**Comment by yuvipanda** [comment]
Moved to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/178
