### ISSUE TITLE
Crashloopbackoff status while installing jupyterhub using helm version 3.3.2

### ISSUE THREAD

**Issue by AnirudhPenmatcha** [jupyterhub/helm-chart#142]
Hi,

I am trying to install jupyterhub using the following command 
`helm upgrade my-jupyterhub jupyterhub/jupyterhub --cleanup-on-fail --install --namespace default --create-namespace --version=3.3.2 --values JH_config.yaml`

But upon running `kubectl --namespace=default get pod`, I see that the pod named hub is not running or crashing for some reason.
![image](https://github.com/jupyterhub/helm-chart/assets/53865153/f64cafb5-f517-4481-b9b2-5e7832a7f391)

**Comment by consideRatio** [comment]
Your config and logs from the hub pod are essential to understand what goes on, raise a question in the forum discourse.jupyter.org please
