### ISSUE TITLE
No stable releases for JupyterHub 5.0 and 5.1?

### ISSUE THREAD

**Issue by krassowski** [jupyterhub/helm-chart#145]
This is a question really, I noticed that there are no stable releases for JupyterHub 5.0 nor 5.1:

![image](https://github.com/user-attachments/assets/23446d30-efd0-4ea0-97e7-5b3b9e8143b2)

Are there any implications for using the development releases instead? Are there plans to tag one of them as stable?

![image](https://github.com/user-attachments/assets/425f9c55-a86c-4c33-ac29-87597e053686)

**Comment by minrk** [comment]
I think we're working on finalizing a kubespawner release, then we'll tag a new version of the chart

**Comment by shlomitubul** [comment]
@minrk to make sure, can I upgrade without a bump chart? like just bump the images (assuming that I don't use / need a feature introduced in the new chart version)

**Comment by minrk** [comment]
I wouldn't guarantee it. That _might_ work, but changes in how the chart makes config available to the image could have happened.

**Comment by shlomitubul** [comment]
Thanks 🙏

**Comment by krassowski** [comment]
FYI this is blocking some folks from upgrading to JupyterHub 5.x, see https://discourse.jupyter.org/t/rtc-add-new-collaboration-groups-dynamically-without-restart-the-hub/27954/5 - given that 5.x includes new security features it _might_ be worth tagging a version as stable if there is no known issues in the helm chart (on our side in https://github.com/nebari-dev/nebari/ we have not encountered any issues and we've been testing it since 5.0 RC and are now on 5.1).

**Comment by consideRatio** [comment]
4.0.0-beta.1 is out! Work to get the release out is tracked in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3406 so I'll close this for now

https://discourse.jupyter.org/t/jupyterhub-helm-chart-4-0-0-beta-1-is-out/28828
