### ISSUE TITLE
license

### ISSUE THREAD

**Issue by minrk** [jupyterhub/helm-chart#21]
This repo uses an Apache license, whereas all other Jupyter repos use BSD 3-Clause. It would be ideal if we could be consistent with the rest of the project.

**Comment by yuvipanda** [comment]
Ideally, I'd eventually want some form of this chart merged upstream into https://github.com/kubernetes/charts/, so everyone using helm can just install it by default. I picked Apache because that repo is Apache.

Easiest might be to dual license, but if not we can always change!

**Comment by minrk** [comment]
If there's an upstream license to reference, that's sensible. I just wanted to make sure there's a reason to deviate from Jupyter defaults. Dual license may be easiest if we can, like you say.

**Comment by yuvipanda** [comment]
It's dual licensed now. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/168 has more things to do.
