### ISSUE TITLE
Steps for deployment on OpenShift.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/helm-chart#26]
Following is steps required for deployment on OpenShift.

1. Create a new project.

```
oc new-project jupyter-helm
```

2. Initialise helm in the new project (don't use default of kube-system).

```
helm init --tiller-namespace jupyter-helm
```

This will deploy ``tiller-deploy``.

3. Grant the ``default`` service account in the project ``cluster-reader`` access. This is necessary as helm wants to be able to read all namespaces for the cluster.

As a cluster admin run:

```
oc policy add-role-to-user cluster-reader -z default -n jupyter-helm
```

4. Grant the ``default`` service account in the project ``edit`` access. This is necessary as helm and JupyterHub need to create resources in the same project.

As a project or cluster admin run:

```
oc policy add-role-to-user edit -z default -n jupyter-helm
```

5. Allow images to be run as any user in project. This is necessary as the Jupyter Notebook images currently must be run as UID 1000 and cannot run as an assigned UID.

As a cluster admin run:

```
oc adm policy add-scc-to-user anyuid -z default -n jupyter-helm
```

6. Create a ``config.yaml`` containing:

```
hub:
  cookieSecret: "RANDOM_STRING_1"
  db:
    type: sqlite-memory
token:
  proxy: "RANDOM_STRING_2"
prePuller:
  enabled: false
singleuser:
  storage:
    type: none
```

Need to disable image pre-puller and use of persistent volumes. Need to work out what other roles need to be granted to allow those.

7. Deploy JupyterHub using helm.

```
helm install https://github.com/jupyterhub/helm-chart/releases/download/v0.3/jupyterhub-v0.3.tgz --name=hub --namespace=jupyter-helm --tiller-namespace=jupyter-helm -f config.yaml
```

Necessary to specify namespace for tiller-deploy and where JupyterHub is to be deployed.

8. Expose the JuptyterHub proxy via a route.

Create ``route.json`` containing:

```
{
    "apiVersion": "v1",
    "kind": "Route",
    "metadata": {
        "name": "proxy-public"
    },
    "spec": {
        "host": "",
        "to": {
            "kind": "Service",
            "name": "proxy-public",
            "weight": 100
        }
    }
}
```

Run:

```
oc create -f route.json
```

Note that you CANNOT run:

```
oc expose svc/proxy-public
```

as it is not setting up the route correctly.

Strangely, creating route from web console for the service does work though. Maybe a bug in ``oc expose``.

**Comment by willingc** [comment]
Thanks @GrahamDumpleton :D

**Comment by GrahamDumpleton** [comment]
The need to disable persistent volumes in OpenShift using:

```
hub:
  db:
    type: sqlite-memory
singleuser:
  storage:
    type: none
```

could be avoided by allowing the storage class for the persistent volume to be optional. This works as OpenShift has a default persistent volume class. By specifying it as a specific value for the storage class it will fail as will not have permission to create a new storage class.

Also, the size of the persistent volume should be configurable as a typical volume claim size is limited to 1GB in OpenShift.

**Comment by GrahamDumpleton** [comment]
Should be highlighted that the need for:

```
oc policy add-role-to-user cluster-reader -z default -n jupyter-helm
```

is because helm for some reason wants to be able to list all namespaces in the cluster and it wouldn't have the ability with default user role in OpenShift for normal user.

**Comment by woopla** [comment]
@GrahamDumpleton I got the route working fine with OpenShift Origin 3.6:
```
oc expose svc/proxy-public --hostname=<host FQDN>
```

The only significant difference with your route.json file is that it adds port 8000 to the config (along with the hostname specified on the command line, but that is necessary in my case, I have to specify the full domain name).

However, the notebook cannot connect to the kernels, I keep getting Websockets timeouts:
1. Notebook pod logfile shows:
```shell
> oc logs jupyter-toto | tail -2
[W 2017-08-25 00:23:43.009 toto zmqhandlers:193] WebSocket ping timeout after 90000 ms.
[I 2017-08-25 00:23:48.112 toto handlers:193] Adapting to protocol v5.1 for kernel a7379c3d-fc2c-4933-91b4-33f4c0e7569e
```
2. JS console in Chrome:
```
Kernel: kernel_reconnecting (a7379c3d-fc2c-4933-91b4-33f4c0e7569e)
kernel.js:459 Starting WebSockets: ws://<host>/user/toto/api/kernels/a7379c3d-fc2c-4933-91b4-33f4c0e7569e
kernel.js:103 Kernel: kernel_connected (a7379c3d-fc2c-4933-91b4-33f4c0e7569e)
manager.js:109 Could not cross validate the widget frontend and backend versions. Error: Timeout while trying to cross validate the widget frontend and backend versions.
    at manager-base.js:180
```
There's a 3s timeout in the Javascript code that outputs this message.

Have you actually tried running a notebook, or did you just try to login to JupyterHub?

Thanks,

Clément

**Comment by GrahamDumpleton** [comment]
@woopla At the time I did that, notebooks were working fine. Versions of different parts have likely changed since and so not surprised if may have problems now, but that could be unrelated to OpenShift itself. Does it work if you do not set a custom external hostname and just rely on hostname generated by OpenShift.

**Comment by woopla** [comment]
@GrahamDumpleton same thing without specifying the host name :(

I just don't know where to start debugging that. I guess it's a routing issue between the browser and the kernel, but HAProxy router logs are not helping:
```
 <142>Aug 25 01:33:57 haproxy[78]: <IP address>:50818 [25/Aug/2017:01:32:20.923] public be_http:jupyter-helm:proxy-public/pod:proxy-deployment-51742714-cn2r3:proxy-public:172.17.0.9:8000 1104/0/0/13/96118 101 266 - - --VN 1/1/0/0/0 0/0 "GET /user/toto/api/kernels/85288896-1b0f-4c1c-aafb-f26e06ab7893/channels?session_id=D426C8BA9D7B4F448ED5BE49486E7173 HTTP/1.1"
```

Also:
```
> oc describe route/proxy-public                                                                                                                                                                                                                                      
Name:			proxy-public
Namespace:		jupyter-helm
Created:		35 minutes ago
Labels:			<none>
Annotations:		openshift.io/host.generated=true
Requested Host:		proxy-public-jupyter-helm.my.company.com
			  exposed on router orw 35 minutes ago
Path:			<none>
TLS Termination:	<none>
Insecure Policy:	<none>
Endpoint Port:		<all endpoint ports>

Service:	proxy-public
Weight:		100 (100%)
Endpoints:	172.17.0.9:8000
```

And:
```
> oc describe svc/proxy-public
Name:			proxy-public
Namespace:		jupyter-helm
Labels:			<none>
Annotations:		<none>
Selector:		name=proxy-pod
Type:			LoadBalancer
IP:			172.30.50.84
External IPs:		172.29.43.194
LoadBalancer Ingress:	172.29.43.194
Port:			<unset>	80/TCP
NodePort:		<unset>	32251/TCP
Endpoints:		172.17.0.9:8000
Session Affinity:	None
Events:			<none>
```

I'm really at a loss where to look for clues 😄 

Thanks,

Clément

**Comment by GrahamDumpleton** [comment]
FWIW, I quickly stopped looking too much into the helm based method of deployment as helm doesn't mesh well with OpenShift. This is because of its requirements to have elevated cluster privileges when used in an OpenShift cluster which has a better security model in place than plain Kubernetes.

If you are interested I can point out my own work on using OpenShift native methods for deployment. Has been a while since I touched it, but it was working last time I tried it. I need to go back and revisit it to finish off some things related to it soon. So depending on what you use case is, you may find it an easier way of getting it working.

**Comment by GrahamDumpleton** [comment]
Interesting timing. Looks like I may have to revisit the helm stuff at least to see where it is at, as project approval been waiting on has come through and have to work again on Jupyter on OpenShift. Maybe we can chat separately about what you are doing if interested.

**Comment by yuvipanda** [comment]
We've merged this repo with https://github.com/jupyterhub/zero-to-jupyterhub-k8s, so let's continue further discussion of this issue on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/177. We do want to have this work out of the box with OpenShift :)
