### ISSUE TITLE
Looking up user details in jupyterhub can fail when container run a uid not in passwd file.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/helm-chart#27]
Under a host service such as OpenShift where the security model results in containers being forced to run as an effective random user ID (not in passwd file), the jupyterhub process will fail to start as it doesn't cope with there being no user in the passwd file.

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 48, in <module>
    from .services.service import Service
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/services/service.py", line 107, in <module>
    class Service(LoggingConfigurable):
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/services/service.py", line 175, in Service
    user = Unicode(getuser(),
  File "/usr/lib/python3.5/getpass.py", line 170, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000090000'
```

Options are to change jupyterhub to be tolerant of this and not fail, or to make ``/etc/passwd`` file writable in Dockerfile and then in startup wrapper script for jupyterhub, add an entry for an assigned UID if not existing in the passwd file. For example:

```
# Ensure that assigned uid has entry in /etc/passwd.

if [ `id -u` -ge 10000 ]; then
    cat /etc/passwd | sed -e "s/^$NB_USER:/builder:/" > /tmp/passwd
    echo "$NB_USER:x:`id -u`:`id -g`:,,,:/home/$NB_USER:/bin/bash" >> /tmp/passwd
    cat /tmp/passwd > /etc/passwd
    rm /tmp/passwd
fi
```

**Comment by yuvipanda** [comment]
I've made a PR for jupyterhub (https://github.com/jupyterhub/jupyterhub/pull/1148) that gets rid of getpass from the default service import path.

**Comment by yuvipanda** [comment]
Closing as the PR to JupyterHub was merged!
