### ISSUE TITLE
Set up and use an nginx ingress by default

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/helm-chart#28]
Even on GKE / Google, we should use an nginx ingress rather than the Google one, since we aren't moving as much traffic and the google one is pretty expensive.

We should stop relying on having a LB per service we want to expose, and set up an Ingress instead. This will also help us in the future when we want to get rid of the proxy and replace it directly with ingress services :)

One feature we do not want to lose is the ability of people to test this with just an IP, without needing a DNS entry. It's ok to require DNS based routing as soon as we have multiple things (such as jupyterhub and binder) but not otherwise.

Current idea is that we'll depend on the nginx-ingress and kube-lego charts, scoped to just the one namespace. These will have to be optional in some form, so non-cloud users with their own ingress controllers can skip these. Instead of setting up LoadBalancer type on Service, we'll just add an ingress object.

**Comment by Analect** [comment]
@yuvipanda 
FYI, Gitlab have simplified a fairly complex set-up using ingress and kube-lego ... close to what you describe above.  Their initial implementation was [here](https://gitlab.com/gitlab-org/kubernetes-gitlab-demo), but they have been updating this to a pure helm installation [here](https://gitlab.com/charts/charts.gitlab.io/tree/master/charts/kubernetes-gitlab-demo/templates) ... although I'm not certain all the kube-lego / ingress stuff is completely implemented as yet.  Still, I think it's worth your time reviewing their approach.
