### ISSUE TITLE
Github Authentication

### ISSUE THREAD

**Issue by jkuruzovich** [jupyterhub/helm-chart#30]
I was trying to get the Github Authentication working.  I saw that it wasn't part of the Helm chart and thought I'd try to add it. 

You can see the changes here.  I'm glad to issue as a pull request but it doesn't seem to be working. 
https://github.com/jupyterhub/helm-chart/compare/master...Kuberlytics:githubauth 

I get no error in the deployment and even after restarting the Hub pod it doesn't seem to use the Github authentication. Not sure if maybe I'm missing something.  

auth:
  type: github
  github: 
    clientId: <enterednumber>
    clientSecret: <hidden secret>
    callbackUrl: http://<myurl>/hub/oauth_callback

When I ssh into the hub it looks like everything was updated properly.

**Comment by yuvipanda** [comment]
heya! that looks like it should work - can you give me a bit more detail on what you mean by "doesn't seem to be working"? Thanks

**Comment by jkuruzovich** [comment]
Thanks! The web interface still presents as if it is the "dummy" based authorization with username/password.  I just deleted everything and tried again just to see. Still getting the same.

**Comment by jkuruzovich** [comment]
I realized I needed to update the hub image.  Just did pull request that should close this.
