### ISSUE TITLE
Rename 'singleuser' to 'user'

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/helm-chart#34]
A lot of people expressed confusion at the fact that all these properties called 'singleuser' exist, but JupyterHub is a multi user deployment. I think this warrants us renaming all the 'singleuser' properties to just 'user'.

**Comment by minrk** [comment]
👍

**Comment by willingc** [comment]
💯

**Comment by choldgraf** [comment]
I think this is something we should change sooner than later, assuming we do want to make this change. The longer that time goes the more people are going to have `singleuser` in their config.yaml files and it'll be a bigger headache when it switches...

**Comment by yuvipanda** [comment]
Moved to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/176
