### ISSUE TITLE
Add configuration to support `svc` annotations

### ISSUE THREAD

**Issue by mtbdeano** [jupyterhub/helm-chart#37]
I'd like to add configuration values to add arbitrary service annotations. In particular, using AWS ELB SSL termination a la https://gist.github.com/mgoodness/1a2926f3b02d8e8149c224d25cc57dc1

**Comment by willingc** [comment]
Hi @mtbdeano, 

Thanks for the suggestion request. At this point in the project development cycle, we are working on vendor agnostic issues/enhancements. I'm going to label this as an "enhancement" in the issue tracker. We're actively developing JupyterHub,and we'll update this issue request as development evolves :sunny:

cc/ @yuvipanda

**Comment by yuvipanda** [comment]
I agree adding arbitrary svc + deployment annotations / labels is a good idea, and has a wide variety of uses.

I'm releasing 0.4 just now, and will work on aligning the chart closer with helm best practices (https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices) after that. This will definitely be part of that!

Thanks for raising it!

**Comment by yuvipanda** [comment]
@mtbdeano I merged this, should be in 0.4 when I release it Monday :)
