### ISSUE TITLE
Storage version mismatch in global template

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/helm-chart#4]
storage.k8s.io/v1beta1 is specified while the expected API version (in 1.6.2) is storage.k8s.io/v1.

**Comment by yuvipanda** [comment]
need to figure out if this happens in GKE 1.6 (See #7)

**Comment by yuvipanda** [comment]
Yup, this is a problem! v1beta doesn't work in 1.6 and v1 doesn't work in 1.5!!! This breaks my understanding of k8s versioning

**Comment by yuvipanda** [comment]
I am pretty sure that this is a helm issue now that version 2.4.0 was supposed to fix - except it has a critical bug preventing it from working (https://github.com/kubernetes/helm/issues/2376).

**Comment by yuvipanda** [comment]
This seems to have gone away with v2.4.1

**Comment by yuvipanda** [comment]
Not anymore! Just make sure you have a recent enough version of helm :)
