### ISSUE TITLE
Public IP Address

### ISSUE THREAD

**Issue by jkuruzovich** [jupyterhub/helm-chart#44]
Previously there was a configuration setting for setting a public IP address. Is that still available?  Might be difficult to get it working with different cloud providers.  However, previously it was working with gcloud.

**Comment by yuvipanda** [comment]
Yup, you can set it as `proxy.service.loadBalancerIP`!

**Comment by jkuruzovich** [comment]
Thanks! Confirmed that this worked fine.  
proxy:
  secretToken: xxxxxxxx
  service:
    loadBalancerIP: 35.xxx.xxx.xxx
