### ISSUE TITLE
Error: PersistentVolumeClaim is not bound: "hub-db-dir"

### ISSUE THREAD

**Issue by gijs** [jupyterhub/helm-chart#49]
Hi,

I'm trying to run this chart on GKE but the deployment keeps failing with `PersistentVolumeClaim is not bound: "hub-db-dir"`.

Steps I took:

- Created a container cluster (v1.7.0)
- `$ kubectl proxy`
- `$ kubectl config current-context`
- Installed Helm (v2.5.0)
- `$ helm init --upgrade`
- Added a file config.yaml:

```yaml
hub:
  cookieSecret: "xxxx"
proxy:
  secretToken: "xxxx"
```
- `$ helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/`
- `$ helm install jupyterhub/jupyterhub --version=v0.4 --name=jupyterhub-test --namespace=jupyterhub-test -f config.yaml`

This resulted in the following output:

```
NAME:   xxxxxx
LAST DEPLOYED: Fri Jul 14 15:30:48 2017
NAMESPACE: xxxxxxx
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME          CLUSTER-IP     EXTERNAL-IP  PORT(S)       AGE
proxy-public  10.31.247.38   <pending>    80:32453/TCP  1s
proxy-api     10.31.241.160  <none>       8001/TCP      1s
hub           10.31.247.218  <none>       8081/TCP      1s

==> v1beta1/Deployment
NAME              DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
hub-deployment    1        1        1           0          1s
proxy-deployment  1        1        1           0          1s

==> v1/Secret
NAME        TYPE    DATA  AGE
hub-secret  Opaque  2     1s

==> v1/ConfigMap
NAME          DATA  AGE
hub-config-1  13    1s

==> v1/PersistentVolumeClaim
NAME        STATUS   VOLUME    CAPACITY  ACCESSMODES  STORAGECLASS  AGE
hub-db-dir  Pending  standard  1s


NOTES:
Thank you for installing JupyterHub!

Your release is named xxxxxxx and installed into the namespace xxxxxx.

You can find if the hub and proxy is ready by doing:

 kubectl --namespace=xxxxxx get pod

and watching for both those pods to be in status 'Ready'.

You can find the public IP of the JupyterHub by doing:

 kubectl --namespace=xxxxxx get svc proxy-public

It might take a few minutes for it to appear!

Note that this is still an alpha release! If you have questions, feel free to
  1. Come chat with us at https://gitter.im/jupyterhub/jupyterhub
  2. File issues at https://github.com/jupyterhub/helm-chart/issues
```

Output from kubectl's `get pod` and `get svc`:

```
$ kubectl --namespace=xxxxx get pod

NAME                              READY     STATUS    RESTARTS   AGE
hub-deployment-820122001-d236w    0/1       Pending   0          1m
proxy-deployment-51742714-tc73p   1/1       Running   0          1m

$ kubectl --namespace=xxxxx get svc

NAME           CLUSTER-IP      EXTERNAL-IP      PORT(S)        AGE
hub            10.31.247.218   <none>           8081/TCP       2m
proxy-api      10.31.241.160   <none>           8001/TCP       2m
proxy-public   10.31.247.38    104.199.48.144   80:32453/TCP   2m

(The external IP for the proxy-public service should be accessible in a minute or two.)
```

Nothing appears on the external IP ofcourse..
Any ideas how I can fix the `PersistentVolumeClaim is not bound: "hub-db-dir"` error?

Thanks!

Gijs

**Comment by yuvipanda** [comment]
Thank you for checking it out!

Can you try `kubectl --namespace=<your-namespace> describe pvc` and show us the output?

**Comment by gijs** [comment]
```
Name:		hub-db-dir
Namespace:	jupyterhub
StorageClass:	standard
Status:		Bound
Volume:		pvc-0836e724-6932-11e7-abba-42010a8400d2
Labels:		<none>
Annotations:	pv.kubernetes.io/bind-completed=yes
		pv.kubernetes.io/bound-by-controller=yes
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/gce-pd
Capacity:	1Gi
Access Modes:	RWO
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  1m		1m		1	persistentvolume-controller			Normal		ProvisioningSucceeded	Successfully provisioned volume pvc-0836e724-6932-11e7-abba-42010a8400d2 using kubernetes.io/gce-pd
```

**Comment by gijs** [comment]
![screen shot 2017-07-15 at 09 51 42](https://user-images.githubusercontent.com/7193/28237601-4342bd4a-6943-11e7-998c-51911cbc03b1.jpg)

**Comment by gijs** [comment]
Any ideas? Did I forget to mount storage while creating the cluster?

**Comment by yuvipanda** [comment]
Hmm, no it should work.. Am not sure why this is happening!

Can you tell us what version of k8s this is (with `kubectl version`)? Also what's the output of `kubectl get storageclass -o yaml`?

**Comment by yuvipanda** [comment]
Can you also provide output of 'kubectl --namespace=<namespace> describe pod -l name=hub-pod'?

**Comment by gijs** [comment]
Will do! (I have to find some time, but I'll report back)

**Comment by aliasmrchips** [comment]
I had the same issue and was able to resolve by pre-creating a persistent volume for the claim to bind to

**Comment by yuvipanda** [comment]
@aculich has found that most of these are because you're running into SSD quota issues - if you don't have a credit card attached, you have a fairly small quota...

**Comment by yuvipanda** [comment]
We've merged this repo into https://github.com/jupyterhub/zero-to-jupyterhub-k8s, and I've moved this issue to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/162. Let's continue the conversation there!
