### ISSUE TITLE
Stress test 999,999,999 users

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/helm-chart#50]
I like to call it the giga test.

**Comment by yuvipanda** [comment]
k8s currently tops out at about 150,000 pods (for their well defined SLOs), so that's kinda where we can aim for at this moment at best :D

**Comment by willingc** [comment]
Try the elixir kernel @choldgraf https://blog.discordapp.com/scaling-elixir-f9b8e1e7c29b Just trolling...

**Comment by yuvipanda** [comment]
We might need to use MongoDB if we need to scale that high!
