### ISSUE TITLE
Add support for LDAP Authenticator 

### ISSUE THREAD

**Issue by viroos** [jupyterhub/helm-chart#55]
https://github.com/jupyterhub/ldapauthenticator

**Comment by viroos** [comment]
Perhaps it could be solved with https://github.com/jupyterhub/helm-chart/pull/53

**Comment by yuvipanda** [comment]
I've moved this to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/173 and think it's a thing we should do in the near future! Thank you for documenting how you have it working right now!
