### ISSUE TITLE
Question: Why do you map jupyterhub config via configmap?

### ISSUE THREAD

**Issue by 21stio** [jupyterhub/helm-chart#59]
Hey,

mapping jupyterhub config via a configmap hides configuration details. Not sure what's the reason for that?

**Comment by yuvipanda** [comment]
Heya @21stio! Can you explain what you mean by 'hides configuration details'? What would you consider a way that does not hide configuration details?

From my pov, we want the helm chart to provide good experience for a supported set of configurations. We express those by allowing various settings in values.yaml. We also allow an escape hatch with the `hub.extraConfig` option. These work well with the kubernetes primitives too (configmap + helm).

**Comment by 21stio** [comment]
Heyo @yuvipanda 

Well to me the user experience was like that. I initially knew how to configure jupyterhub and how to deploy to kubernetes. So I deployed jupyterhub via helm. When I wanted to customize the configuration I had to figure out what's the intention of the configmap. I expected it to be the jupyterhub config, but instead I found a bunch of kv pairs. So I had to figure how it's used to turn it into the jupyterhub config and how to inject stuff that isn't injectable by just changing some release values..

I got your point regarding good experience, but to me it feels weird to write configuration to configure a jupyterhub config. Plus, I guess maintaining this approach isn't fun too (PRs for the jupyterhub_config.py)

just my 2 cents

**Comment by yuvipanda** [comment]
Thanks for the comments, @21stio! 

What would your ideal workflow look like?

**Comment by 21stio** [comment]
I'm not sure if I get your question right. 

If your asking me how I'd done it, I'd have just mounted the config directly. The entiry config could be stored in the values.yaml, which is turned into a config map with one key which is then mounted into the pod.

The `hub.extraConfig` option is sufficient to inject necessary configuration indeed, but it's a little bit misleading.

**Comment by yuvipanda** [comment]
Ah, ok!

yeah, this helm-chart is definitely aimed at a different audience, I guess :) Abstracting away implementation details like this works well with the Zero to JupyterHub guide (z2jh.jupyter.org) that is the primary documentation for this. Advanced users who want total control and one less level of abstraction should find it quite easy to just roll a more bare bones chart themselves. If you have one (or are interested on making one!) that'd be great - we'll happily link to that from here!

**Comment by 21stio** [comment]
hm Im not really using Helm.. I just did helm install --debug --dry-run and copied to rendered yaml.

But yeah thanks for the chat! Good to be closed ;)
