### ISSUE TITLE
CPU guarantee parsing error

### ISSUE THREAD

**Issue by philwinder** [jupyterhub/helm-chart#69]
I tried to set the CPU limits as specified in the docs, but it didn't start due to the following error:

```
    traitlets.traitlets.TraitError: The 'cpu_guarantee' trait of a KubeSpawner instance must be a float, but a value of '500m' <class 'str'> was specified.
```

Setup:

```yaml
  cpu:
    limit: 500m
    guarantee: 500m
```

Versions:

- jupyterhub-v0.4
- Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
- Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by willingc** [comment]
Hi @philwinder, 

You are using a version of JupyterHub 0.4 that is quite old. We are currently at 0.7.2 stable and 0.8.0b4 beta as the latest version. I would try upgrading jupyterhub.

**Comment by yuvipanda** [comment]
@willingc i think he means v0.4 of helm chart, which is jupyterhub 0.7.2.

I think the CPU guarantee and limits are floats - 500m is expressed as 0.5
I think. Can you try that?

**Comment by philwinder** [comment]
Sorry, yes, I meant the helm chart version 0.4. Yes I will try 0.5.

**Comment by choldgraf** [comment]
@yuvipanda if that's the case, we should change the documentation:

https://zero-to-jupyterhub.readthedocs.io/en/latest/user-experience.html#allocating-and-controlling-user-resources

I'll open the PR if that's what resolves the issue.

**Comment by willingc** [comment]
It would be nice to update the output to say helm-jupyterhub and not just jupyterhub too.

**Comment by yuvipanda** [comment]
Yeah the docs are wrong :(

**Comment by philwinder** [comment]
I can confirm that `0.5` works.

**Comment by philwinder** [comment]
However, I can't seem to set the request (guarantee) on the memory? What's the format for that?

These don't work:
```
  mem:
    guarantee: 256000000
  mem:
    guarantee: 256Mi
  mem:
    guarantee: 256
```

K8s continues to report (from `kubectl describe`):
```
    Requests:
      cpu:      500m
      memory:   1073741824
```

**Comment by choldgraf** [comment]
what about `.25G`?

**Comment by choldgraf** [comment]
(or try `250M`)

**Comment by choldgraf** [comment]
alternatively (I promise this is the last comment) can you try the things above that *didn't* work, but put them in quotes? E.g., `memory: "256M"`

**Comment by philwinder** [comment]
Oh goodness me.
The issue was the key, `mem`. It's not mem, its `memory`.

**Comment by philwinder** [comment]
And despite the k8s definition of mem, `Mi` causes a crash. It has to be `M` or `G`.

This page is particularly helpful for figuring out what is required:

https://github.com/jupyterhub/helm-chart/blob/master/jupyterhub/values.yaml#L95

**Comment by philwinder** [comment]
Closed, as I see you have a PR to merge to fix the cpu entry.

Thanks, for you help @choldgraf and @yuvipanda

**Comment by philwinder** [comment]
One final thing, `memory` has to be an integer. It doesn't accept `1.5G`, for example.

**Comment by Ajay2307** [comment]
Hi,

I deployed jupyterhub on EKS.
I am getting the below error when I am setting CPU limit for the single-user server in jupyterhub_config.py file

Error: The 'cpu_limit' trait of a KubeSpawner instance must be a float, but a value of '1' <class 'str'> was specified.

So I set the cpu_limit value in the floating-point type i.e cpu_limt= '1.00'

Again also same error
Error: The 'cpu_limit' trait of a KubeSpawner instance must be a float, but a value of '1.00' <class 'str'> was specified.

Spawner config in Jupyterhub_config.py file:

c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner' 
c.KubeSpawner.profile_list = [
{
'display_name': 'Minimal Notebook',
'kubespawner_override': {
'image_spec': 'docker.io/jupyter/minimal-notebook:latest',
'cpu_limit': '1.00',
'mem_limit': '1G',
'cpu_guarantee': '0.5',
'mem_guarantee': '1G' 
}
}

Can I have a solution, please!

**Comment by consideRatio** [comment]
@Ajay2307 remove the quotes from 1.00.

1.00 is a float but '1.00' is a string.

**Comment by Ajay2307** [comment]
Great thanks @consideRatio 
It is working for me!!!
