### ISSUE TITLE
Some guidance on the appropriate settings in getting helm-chart for jupyterhub 0.8x working

### ISSUE THREAD

**Issue by Analect** [jupyterhub/helm-chart#70]
Posting as an issue on the advice of @willingc [here](https://gitter.im/jupyterhub/jupyterhub?at=59b17d72bc46472974087088).

I'm revisiting testing jupyterhub 0.8 in a kubernetes context, using the jupyterhub/helm-chart, to try to get multi-server per user working ... having initially hacked on this at jupytercon. 

As I understand it, there have been some changes to how the proxy is set up in the context of jupyterhub v0.8 (as against v0.7.2), so perhaps someone could wade in here and help clear things up.

I did try to run the [jupyterhub-0.8](https://github.com/jupyterhub/helm-chart/tree/jupyterhub-0.8) feature branch in this repo, which doesn't use the `configurable-http-proxy`, but I couldn't get that working and it looks like it might be superseded by updates to master in any case.

From a brief discussion with @minrk at jupytercon, it seems there is a built-in proxy with jupyterhub, but since the set-up in this helm chart makes use of an external proxy, it's necessary to switch off the internal one using the `c.ConfigurableHTTPProxy.should_start = False` setting in the jupyterhub_config.py file that forms parts of the hub image.  I have also played-around with setting `c.ConfigurableHTTPProxy.api_url`, which replaces the deprecated `c.JupyterHub.proxy_api_ip` and  `c.JupyterHub.proxy_api_port `settings.

An excerpt from my jupyterhub_config.py looks like this:
```
# Requirements for multi-server per user
c.ConfigurableHTTPProxy.should_start = False
c.JupyterHub.allow_named_servers = True
c.ConfigurableHTTPProxy.api_url = 'http://' + os.environ['PROXY_API_SERVICE_HOST'] + ':' + os.environ['PROXY_API_SERVICE_PORT']
# Connect to a proxy running in a different pod
#c.JupyterHub.proxy_api_ip = os.environ['PROXY_API_SERVICE_HOST']
#c.JupyterHub.proxy_api_port = int(os.environ['PROXY_API_SERVICE_PORT'])
```
My understanding, as per the zero-to-hub docs, is that feeding a `config.yaml` file on starting the chart via helm, will over-ride any defaults in the `values.yaml` file, which in turn go to feed various parameter settings in the jupyterhub helm templates.  Note that I'm installing the helm chart from a local directory (to allow me to make changes) rather than using the host chart as per the `helm repo add jupyterhub https://jupyterhub.github.io/helm-chart` step in the zero-to-hub docs.

My `config.yaml` is starting out very simple (see below) ... using a home-grown hub image with 0.8.0b4 installed ... and using the `latest` configurable-http-proxy (I also tried with v. 2.0.4). I'm using a singleuser image which I'm presuming also has the latest jupyterhub, but I didn't get far enough to test that.  The hub image is built using [this](https://gist.github.com/Analect/7c83460177a7df10fad0b447b8105424) Dockerfile ... where I'm trying to use the latest kubespawner master.  If I should be using a jupyterhub-onbuild as my base to which I then add kubespawner, then please advise.

```
hub:
  cookieSecret: "0ec46355dae0c7368dbaxxxxxxxxxxxxxxxx<and so on>"
  image:
    name: myregistry/jupyterhub-k8s
    tag: v0.8.0b4
proxy:
  secretToken: "041123858273121bd51594f4f4xxxxxxxxxxxxxxxx<and so on>"
  image:
    name: jupyterhub/configurable-http-proxy
    tag: latest
singleuser:
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: veadcd78
```

The upshot is that I'm still getting these errors in the proxy logs:
```
14:17:27.730 - debug: [ConfigProxy] PROXY WEB / to http://hub-deployment-1491691835-lw135:8081
14:17:27.749 - error: [ConfigProxy] 503 GET / Error: getaddrinfo ENOTFOUND hub-deployment-1491691835-lw135 hub-deployment-1491691835-lw135:8081
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```
The `hub-deployment-1491691835-lw135:8081` makes me think that its coming from the proxy start command in `values.yaml` ... ie. `--default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)` ... which would explain why it's pointing back at the name of the hub pod (although I'm not sure why it's not using the ip).

... and this in the hub logs.
```
[I 2017-09-07 14:15:34.109 JupyterHub app:1541] Not starting proxy
[I 2017-09-07 14:15:34.109 JupyterHub app:1547] Starting managed service cull-idle
[I 2017-09-07 14:15:34.110 JupyterHub service:266] Starting service 'cull-idle': ['/usr/bin/python3', '/usr/local/bin/cull_idle_servers.py', '--timeout=3600', '--cull_every=600']
[I 2017-09-07 14:15:34.119 JupyterHub service:109] Spawning /usr/bin/python3 /usr/local/bin/cull_idle_servers.py --timeout=3600 --cull_every=600
[W 2017-09-07 14:15:34.148 JupyterHub proxy:304] Adding missing default route
[I 2017-09-07 14:15:34.149 JupyterHub proxy:370] Adding default route for Hub: / => http://hub-deployment-1491691835-lw135:8081
[I 2017-09-07 14:15:34.159 JupyterHub app:1584] JupyterHub is now running at http://10.7.254.59:80/
[I 2017-09-07 14:15:34.321 JupyterHub log:122] 200 GET /hub/api/users (cull-idle@10.4.1.2) 6.12ms
[I 2017-09-07 14:16:10.651 JupyterHub log:122] 302 GET /503?url=%2F \u2192 /hub/503?url=%2F (@10.4.4.119) 3.23ms
[I 2017-09-07 14:16:13.288 JupyterHub log:122] 302 GET /503?url=%2F \u2192 /hub/503?url=%2F (@10.4.4.119) 0.63ms
[I 2017-09-07 14:17:27.752 JupyterHub log:122] 302 GET /503?url=%2F \u2192 /hub/503?url=%2F (@10.4.4.119) 0.64ms
[I 2017-09-07 14:25:34.418 JupyterHub log:122] 200 GET /hub/api/users (cull-idle@10.4.1.2) 5.26ms
```
The `503` errors above are when I'm trying to hit the endpoint of the proxi-api service end-point, to no avail.

Perhaps it has something to do with the default settings in the helm-chart [here](https://github.com/jupyterhub/helm-chart/blob/master/jupyterhub/values.yaml#L35-L53) ... which are somehow over-riding what's getting set in the jupyterhub_config.py.

In there a 'target' is being set using the 'hub' ip ... whereas the `c.ConfigurableHTTPProxy.api_url` setting suggests pointing at the 'proxy-api' ip. Could someone confirm if I should try to remove this command for the proxy in the `values.yaml` in order for things to work against jupyterhub 0.8x ... and instead use c.ConfigurableHTTPProxy.command from the jupyterhub_config.py to control how the proxy is started.

I'm ultimately trying to test the multi-server per user feature of jupyterhub 0.8 in a kubernetes context ... so getting a stable functioning hub to begin with is the main objective of this issue.

**Comment by yuvipanda** [comment]
You should use the v0.5.x branch. It's tracking JupyterHub 0.8, and will be merged to master after 0.8 is released :)

**Comment by Analect** [comment]
@yuvipanda 
Thanks.  I tried using the 0.5x branch ... updating the hub version used in the hub and single-user images to v0.8.0b5.  Things partly worked, but there appear to be still issues in starting named-servers via the API. Perhaps, we can troubleshoot together.

1. As per above, with hub and user-image upgraded to use JupyterHub v0.8.0b5, if I run the following commands via the API using a generated token, things work ... I am able to start and stop a server.

`curl -v -X POST -H "Authorization: token 9ac2487fb43c42998a5390f0b1f559ad" "http://<proxy-api-service-ip>/hub/api/users/testuser/server"`

`curl -v -X DELETE -H "Authorization: token 9ac2487fb43c42998a5390f0b1f559ad" "http://<proxy-api-service-ip>/hub/api/users/testuser/server"`

2. By default, the `jupyterhub_config.py` is missing the setting to enable named servers `c.JupyterHub.allow_named_servers = True`.  I add this and regenerated a new hub image with tag `v0.8.0b5_ns`, which I deploy.

Now if I try to launch a server (as per 1 above), it fails, citing the absence of a `default_server_name` ...  as per hub logs below.

```
[I 2017-09-12 09:57:33.120 JupyterHub log:122] 200 GET /hub/login?next=%2Fhub%2Fuser%2Fmccoole%2Fapi%2Fcontents%2Futilities%3Fcontent%3D1%261505210253011 (@10.132.0.4) 1.72ms
[E 2017-09-12 09:57:41.151 JupyterHub web:1590] Uncaught exception POST /hub/api/users/testuser/server (10.132.0.6)
    HTTPServerRequest(protocol='http', host='35.195.231.59', method='POST', uri='/hub/api/users/testuser/server', version='HTTP/1.1', remote_ip='10.132.0.6', headers={'X-Forwarded-For': '10.132.0.6', 'Content-Length': '0', 'User-Agent': 'curl/7.52.1', 'Authorization': 'token 9ac2487fb43c42998a5390f0b1f559ad', 'X-Forwarded-Port': '80', 'Connection': 'close', 'Accept': '*/*', 'X-Forwarded-Proto': 'http', 'Host': '35.195.231.59', 'X-Forwarded-Host': '35.195.231.59'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/lib/python3.5/types.py", line 199, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/apihandlers/users.py", line 189, in post
        server_name = user.default_server_name()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 226, in __getattr__
        raise AttributeError(attr)
    AttributeError: default_server_name
    
[E 2017-09-12 09:57:41.157 JupyterHub log:114] {
      "X-Forwarded-For": "10.132.0.6",
      "Content-Length": "0",
      "User-Agent": "curl/7.52.1",
      "Authorization": "token [secret]",
      "X-Forwarded-Port": "80",
      "Connection": "close",
      "Accept": "*/*",
      "X-Forwarded-Proto": "http",
      "Host": "35.195.231.59",
      "X-Forwarded-Host": "35.195.231.59"
    }
[E 2017-09-12 09:57:41.158 JupyterHub log:122] 500 POST /hub/api/users/testuser/server (testuser@10.132.0.6) 10.57ms
```
I was under the impression that v0.8 of jupyterhub extended the options vis a vis launching servers ... that a call to `/hub/api/users/testuser/server` ... would start a default server for user `testuser` ... based on the default `singleuser.image.name`.  However, this is not the behaviour I'm getting.

3. If I then try to start a 'named-server' via the api, I get a `404` error (as per logs below), which suggests that the API is somehow not expecting a named-server to be started in this way.  Perhaps I have misunderstood the proper syntax:

`curl -v -X POST -H "Authorization: token 63370e856bcd447bbd94acfa85375208" "http://35.195.231.59/hub/api/users/testuser/server/test1"`

The command above I thought was going to start a named-server called `test1` against user `testuser`.

Response from this curl command:
https://gist.github.com/Analect/a245b221bebecc445e6e438c628daf9c

There were no relevant logs from the hub, suggesting that this command never properly reached the hub.

4.  Another thing I notice, which may or may not be relevant ... is that if I `kubectl exec` into the hub pod ... I can see two separate processes running jupyterhub ... should that be the case?

```
jovyan@hub-deployment-2645688848-qkxmg:/srv$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
jovyan       1  0.0  0.0   4496   764 ?        Ss   09:48   0:00 /bin/sh -c jupyterhub --config /srv/jupyterhub_config.py --no-ssl
jovyan       5  0.7  1.8 313920 71620 ?        Sl   09:48   0:02 /usr/bin/python3 /usr/local/bin/jupyterhub --config /srv/jupyterhub_config.py -
jovyan      12  0.0  0.6  79340 22952 ?        Ss   09:48   0:00 /usr/bin/python3 /usr/local/bin/cull_idle_servers.py --timeout=3600 --cull_ever
jovyan      13  0.0  0.0  18372  3404 ?        Ss   09:52   0:00 /bin/bash
jovyan      27  0.0  0.0  36832  2916 ?        R+   09:53   0:00 ps aux
```

**Comment by yuvipanda** [comment]
For 2, you can use the `hub.extraConfig` option, which allows setting arbitrary python code to be loaded as jupyterhub_config.

For 4, I see only one jupyterhub process - I see a `/bin/sh` that launched the jupyterhub process and the jupyterhub process. This feels normal.

For the named servers question, unfortunately I've not really played with them and am unsure how they work. @minrk might be able to help, but it might also be easier to open them in the JupyterHub repo / try to reproduce them in a simple setup outside of kubernetes. Multiple servers per user is a pretty bleeding edge feature IIRC.

**Comment by Analect** [comment]
Ref 2, so an alternative way of adding that setting to jupyterhub_config.py is extending the `config.yaml` as follows?

```
hub:
  extraConfig:
    allow_named_servers: True
```
Still, with the approach I took of manually adding it, it seems it got picked-up and it is still adversely affecting how servers are launched via the API.

Ref 4 ... I'll take your word for it.

As you said, some of these topics related to the API and its usage for launching servers and named-servers are more @minrk domain ... it would be nice to get them working in a kubernetes context ahead of the 0.8x release. I haven't tried to get them running in a simplified (outside a kubernetes) context ... but I suppose I can try.
