### ISSUE TITLE
make chart fails with "No rule to make target chart"

### ISSUE THREAD

**Issue by Winterflower** [jupyterhub/helm-chart#71]
Hello Jupyterhub team, 
I have made some customisation to the default helm chart. The *Usage" section in the README states that I can package a custom chart using  
``make chart``
however this throws a "No rule to make target 'chart' error.
Has this been depreated?

**Comment by yuvipanda** [comment]
Try `make package-chart`? 

I'm redoing the README just now :)

**Comment by Winterflower** [comment]
ok :) will try today, thank you @yuvipanda 
btw, will there be support for native helm commands at some point (like helm package)? I tried to run ``helm-package`` using the helm-chart I checked out. I then deployed it on the K8s cluster, but unfortunately the hub pod was failing. Would like to help drive this fwd if the project will at some point support native helm.

**Comment by yuvipanda** [comment]
Have moved this to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/175! Let's continue discussion there.
