### ISSUE TITLE
Hub in State Crash for jupyterhub/k8s-hub:b2fb7a6 or jupyterhub/k8s-hub:b2fb7a6:627ff35

### ISSUE THREAD

**Issue by ILoveDataSCIENCE8** [jupyterhub/helm-chart#72]
see below.

**Comment by jkuruzovich** [comment]
(Sorry, made issue with testing account).
@minrk
When pulling either hub image b2fb7a6 or 627ff35 I get an issue with the hub going into a "CrashLoopBackOff" state. As b2fb7a6 was my pull request (627ff35 looks harmless) I've been just trying to figure out if I broke something.

#65
Best,
Jason

**Comment by ILoveDataSCIENCE8** [comment]
Closing this. Sorry. I think there are other things going on with my instance.
