### ISSUE TITLE
After scaling cluster from 0 to x, external IP address times out

### ISSUE THREAD

**Issue by philwinder** [jupyterhub/helm-chart#73]
I was following the recommendations to scale the cluster to 0, the scale up on the day as per: https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#expanding-and-contracting-the-size-of-your-cluster

But when scaling back up, the main external IP address just times out.

I can't quite seem to find the problem. The LB is pointing to the service. The service is pointing to the proxy. The proxy is pointing to the Hub. It's almost like the hub is binding to the wrong IP address.

I'll add more information if I find it.

**Recreate**:

Standard instructions to create a cluster, add helm, install jupyter hub.

Then resize to zero nodes:
```
gcloud container clusters resize ${CLUSTER_NAME} --size 0 --zone ${ZONE}
```
Wait for that to finish. Then scale back up. I made the size different to the original size. Not sure if that made any difference.
```
gcloud container clusters resize ${CLUSTER_NAME} --size 5 --zone ${ZONE}
```

**Workaround**
Don't scale down your cluster to zero. Always make sure you have at least one node running.

**Edit 1**
This only occurs if you resize to a number of nodes that was NOT your original size.

In fact, I can fix a broken cluster by scaling from 5 (not original) to 3 (original).

**Edit 2**
Scaling from the original size, to another larger size works. This implies that there is some dependence on the hub running in the same place, or at least one of the original nodes. I'm not sure.

**Comment by choldgraf** [comment]
this is .... strange.... :-)

Thanks for the careful debugging. We definitely don't want that external IP to change (I feel like it *shouldn't* since if you scale the cluster down to 0 you should still be paying for the IP address).

@aculich do you have any experience scaling clusters up/down in this way? Ever experienced instability in the network configuration as a result?

**Comment by philwinder** [comment]
I don't think the external address ever changed, as that was held for me by google cloud.

And when everything restarted, all the k8s components did appear to be pointing to the right ip addresses. It seemed like it was jupyter hub that was source of the problem, although I couldn't see what.

**Comment by yuvipanda** [comment]
hmm, I've had scaling up and down work very well in the past. Let's try to debug this :)

1. Can you provide output of `kubectl --namespace=<your-namespace> get pod -o yaml`? 
2. Can you provide output of `kubectl --namespace=<your-namespace> describe pod`?

Based on these, we can tell if the pods are running or not, and what stage they're in. We can then go from there.

**Comment by yuvipanda** [comment]
We've merged this repo with https://github.com/jupyterhub/zero-to-jupyterhub-k8s, and I've move this issue over to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/181. Please continue the conversation there, we wanna help you get this to work!
