### ISSUE TITLE
allow jupyterhub_config.py

### ISSUE THREAD

**Issue by minrk** [jupyterhub/helm-chart#76]
Writing Python in yaml is pretty painful for nontrivial content. Is there a way to get a standalone `jupyterhub_config.py` file that is loaded the same as `hub.extraConfig` in yaml?

**Comment by choldgraf** [comment]
from a user standpoint I think that'd make things easier...seems like it's possible: https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/accessing_files.md

**Comment by yuvipanda** [comment]
Unfortunately that's not a feature we can use. The accessing_files.md documentation is for accessing files *inside* the packaged chart, rather than for users using helm install / upgrade. I agree it would be much better, but helm doesn't have that feature right now.

**Comment by minrk** [comment]
Fair enough. Consider this wishlist, waiting on upstream.

**Comment by yuvipanda** [comment]
Moved to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/179
