### ISSUE TITLE
Small error in /images/hub/Dockerfile

### ISSUE THREAD

**Issue by danroliver** [jupyterhub/helm-chart#77]
When the docker image is being built for the hub, the following error is raised. 
```
Collecting git+https://github.com/jupyterhub/kubespawner@804947a
  Cloning https://github.com/jupyterhub/kubespawner (to 804947a) to /tmp/pip-oqdowm7a-build
  Could not find a tag or branch '804947a', assuming commit.
```

The problem is with line 37 in /images/hub/Dockerfile
```
RUN pip3 --no-cache-dir install git+https://github.com/jupyterhub/kubespawner@804947a
```
which can be corrected with:
```
RUN pip3 --no-cache-dir install https://github.com/jupyterhub/kubespawner/archive/v0.6.0.zip
```

**Comment by yuvipanda** [comment]
@danroliver is that an actual error? 8094947a is a commit hash, and that's what's being explicitly used. We don't want v0.6.0...

**Comment by minrk** [comment]
That's pip debug output showing that there is no tag '804947a', so it's assuming (correctly) that it's a commit and proceeding. I don't think there are any errors here.

**Comment by danroliver** [comment]
For some reason, I thought it was grabbing latest. I wasn't reading closely enough. Regardless, for the specific commit that you want, the syntax:
```
RUN pip3 --no-cache-dir install https://github.com/jupyterhub/kubespawner/archive/804947abc321cf0433aa7608f82efc5316057802.zip
```
will not issue the warning and runs more quickly.
