### ISSUE TITLE
Make disk storage work on Azure

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/helm-chart#8]
Make sure that we can have the entire thing (including Sqlite PVC + per-user pod PVC)

**Comment by jameswinegar** [comment]
I'm guessing this is related to this issue `SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "hub-db-dir"?

Did not want to duplicate issues.

**Comment by yuvipanda** [comment]
with 0.4 of helm-chart, disk attaches do work on Azure. However, Azure has a really low limit on disks per node (about 4?) making it impractical for use with this helm chart right now. The 'azure file' provisioner might be able to help soon tho
