### ISSUE TITLE
Merged with zero-to-jupyterhub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/helm-chart#81]
This repo's been merged with z2jh. There's still a lot over here that isn't merged

We still need to migrate helm-chart docs and all Issues here over to there. Do the low-level 'developing on the helm charts' docs belong in the z2jh rest docs, or a separate docs location in the same repo, since now there are two separate things to document?

Once issues have been migrated, we need to disable Issues and pull requests on this repo and update the README to point to the new home.

**Comment by yuvipanda** [comment]
Yeah, I had a TODO in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/162#issuecomment-330414694. Going to continue with it.

**Comment by yuvipanda** [comment]
Going to close this, as I'm almost done moving all the issues.
