### ISSUE TITLE
Un-deprecate this repo

### ISSUE THREAD

**Issue by willingc** [jupyterhub/helm-chart#82]
As significant time has gone by since we migrated content from this repo to z2jh, it may be helpful to undeprecate the repo, update the README, and set the default branch to gh-pages.

cc/ @yuvipanda @choldgraf @minrk

**Comment by minrk** [comment]
👍 . @yuvipanda mentioned that it would probably be cool to have a nice table view of the index as the index.html, which would help discover the latest version.

**Comment by willingc** [comment]
Ok.
I'm going to:
- remove deprecated from repo description
- update the README
- set the default to gh-pages
