### ISSUE TITLE
Create a table view of the charts in index.html

### ISSUE THREAD

**Issue by willingc** [jupyterhub/helm-chart#83]
@yuvipanda mentioned it would be helpful to have a table to make discovery of the latest chart more user friendly.

**Comment by costrouc** [comment]
Had the hardest time finding the most current release of v0.5.0-.... would definitely second some ordered list of releases.

**Comment by willingc** [comment]
Marking as resolved as the website (https://jupyterhub.github.io/helm-chart/) does a good job of displaying an index of versions.
