### ISSUE TITLE
Deployment fails on pre-puller on Azure/ACS

### ISSUE THREAD

**Issue by ams0** [jupyterhub/helm-chart#85]
If I don't add `--set prePuller.enabled=false` helm deployment fails. Upon inspection, I noticed that this [script](https://github.com/yuvipanda/kube-image-puller/blob/master/pull-allnodes/allnodes.sh) in `yuvipanda/image-allnodes-puller:v0.8` image fails. The output of `kubectl get node` is, on Azure, like this:

```
/tmp # kubectl get nodes
NAME                    STATUS         AGE
k8s-agent-2c182d23-0    Ready,agent    7h
k8s-agent-2c182d23-1    Ready,agent    7h
k8s-master-2c182d23-0   Ready,master   7h
```

so fails to match the `awk '{ if ($2 == "Ready") print $1; }'` filter.
I'm not sure this can be universally fixed for all clouds, I just wanted to report the issue, perhaps docs at http://zero-to-jupyterhub.readthedocs.io/en/v0.4-doc can be amended.

**Comment by choldgraf** [comment]
thanks for reporting this! @yuvipanda can you confirm a bug in the docs and if so I can make a PR to add `--set prePuller.enabled=false`?

As a quick note @ams0 , we wrote those docs before the new container service was announced. We're trying out the process w/ the new setup to see what's different, what's broken, etc, but YMMV in the meantime! These kinds of doc-improving PRs are very welcome!

**Comment by yuvipanda** [comment]
@choldgraf I don't think this is related to the new AKS announcement from Azure, I think this is still set up with tolder acs-engine. Disabling pre-puller is a workaround, this is a bug in the prepuller.

@ams0 can you tell us which version of kubernetes you are running? That output looks different than on my cluster!

**Comment by ams0** [comment]
@yuvipanda I'm running 1.7.7 straight off ACS (no acs-engine). 

Now that I come to think of it, perhaps this is due to the old version of `kubectl` that is pulled by the docker container (https://github.com/yuvipanda/kube-image-puller/blob/master/pull-allnodes/Dockerfile#L7)

```
ADD https://storage.googleapis.com/kubernetes-release/release/v1.5.4/bin/linux/amd64/kubectl /usr/local/bin/kubectl
```
I'm gonna rebuild with kubectl 1.7.7 and try that out.

**Comment by yuvipanda** [comment]
@ams0 cool! any luck?

**Comment by willingc** [comment]
After the Azure testing the other day, I'm going to go ahead and close this. If you are having issues still @ams0, please let us know and we can reopen or open a new issue. Thanks.
