### ISSUE TITLE
Hub Deployment in CrashLoopBackoff - more debugging help in documentation might be needed

### ISSUE THREAD

**Issue by randguth** [jupyterhub/helm-chart#86]
I have read the debugging help in the z2jh documentation, and was hopeful when I saw explicit guidance for debugging CrashLoopBackoff.  I have deleted and deployed my hub three or four times, and rewritten the config.yaml file the same number of times with new tokens, and still am getting the CrashLoopBackoff.  

My log states:
```
C:\helm>kubectl --namespace=mithub1 logs hub-deployment-1176542735-gdmwb
[I 2017-11-30 13:27:51.211 JupyterHub app:720] Loading cookie_secret from env[JPY_COOKIE_SECRET]
[E 2017-11-30 13:27:51.212 JupyterHub app:1527]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 1524, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.5/types.py", line 199, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 1306, in initialize
        self.init_secrets()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 721, in init_secrets
        secret = binascii.a2b_hex(secret_env)
    binascii.Error: Non-hexadecimal digit found

singleuser.storage.type dynamic
singleuser.storage.capacity 10Gi
singleuser.storage.home_mount_path /home/jovyan
singleuser.memory.guarantee 1G
auth.type dummy
admin.access True
cull.enabled True
cull.timeout 3600
cull.every 600
hub.base_url /
hub.db_url sqlite:///jupyterhub.sqlite
singleuser.cmd jupyterhub-singleuser
```

I'm at a loss of what I might be doing wrong, or what else I might try.  If there is some subtlety in how to make that file, or otherwise figure out what might be causing this, I think the documentation would benefit from additional explanation.

**Comment by choldgraf** [comment]
can you paste the contents of `config.yaml`? also double-check that your SSL tokens are correct!

**Comment by willingc** [comment]
Thanks for the suggestion @randguth. The documentation has a [debugging section when `CrashLoopBackoff` occurs](http://zero-to-jupyterhub.readthedocs.io/en/latest/debug.html?highlight=crashloopbackoff#hub-fails-to-start).
