### ISSUE TITLE
Broken link to 0.8.0

### ISSUE THREAD

**Issue by Reedlee** [jupyterhub/helm-chart#95]
What I do:
```
Given I open page https://github.com/jupyterhub/helm-chart#versions-coupled-to-each-chart-release
When I clicked on 0.8.0 from column Associated files
Then browser opens https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.8.0/images/hub
```
What I see:
`And I see that page not found`
What I expected to see:
`And I see a page with files for tag 0.8.0`

**Comment by choldgraf** [comment]
I believe this is because 0.8 is not yet released, but we should make this clearer in the link!
