### ISSUE TITLE
Make this Helm chart repository available on Helm Hub

### ISSUE THREAD

**Issue by desaintmartin** [jupyterhub/helm-chart#98]
The Helm Hub (https://hub.helm.sh/) provides a way to expose Charts and will be used as the canonical way to search for Charts in Helm 3.

https://github.com/helm/hub/blob/master/Repositories.md

Unfortunately, I can't find the chart in the hub.

**Comment by consideRatio** [comment]
I agree, we should strive for this. We need to make sure to comply with their expectations first though, which can be quite an effort for us. After we have done that, the rest seem quick and easy.

# Expected practices
We are expected to comply with the regular [Helm chart best practices](https://helm.sh/docs/chart_best_practices/) and some additional ones listed below.

## JupyterHub
- [ ] Every chart to have a maintainer listed along with valid contact information for each maintainer. The contact information could be in the form of an email address or link to a contact form
- [ ] Charts to pass Helm lint, be installable and upgradable in all community supported versions of Kubernetes, and to use semantic versioning to share intent in released changes. To help with this we suggest leveraging the Chart Testing project.
- [ ] Have a NOTES.txt template with useful information which Helm will display after installation
- [ ] Chart versions to be immutable

## BinderHub
- [ ] Every chart to have a maintainer listed along with valid contact information for each maintainer. The contact information could be in the form of an email address or link to a contact form
- [ ] Charts to pass Helm lint, be installable and upgradable in all community supported versions of Kubernetes, and to use semantic versioning to share intent in released changes. To help with this we suggest leveraging the Chart Testing project.
- [ ] Have a NOTES.txt template with useful information which Helm will display after installation
- [ ] Chart versions to be immutable

**Comment by manics** [comment]
See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1517
